### ISSUE TITLE
API key is sent in a strange way

### ISSUE THREAD

**Issue by boris-petrov** [airbrake/javabrake#16]
On this line:

https://github.com/airbrake/javabrake/blob/master/src/main/java/OkSender.java#L53

The `projectKey` is being sent via a header `X-Airbrake-Token` instead of the "normal" way - with a query parameter:

`http://aibrake.io/api/v3/projects/0/notices?key=aaaaaaaaaaa`

Why is this? Is this supposed to work?

**Comment by vmihailenco** [comment]
Yes, it works and it is done that way to hide token from the Apache/nginx/haproxy logs.

**Comment by boris-petrov** [comment]
I see, thanks for the support!
