### ISSUE TITLE
clarify the role of X-Airbrake-Token header

### ISSUE THREAD

**Issue by stevecrozz** [airbrake/javabrake#17]
In the Airbrake API docs, I see no mention of X-Airbrake-Token, but instead the key is called out as part of the query string: https://airbrake.io/docs/api/#authentication.

I'd be interested to know why this OkSender class: https://github.com/airbrake/javabrake/blob/9953317c70fe2307d91b8573a7588b6ea5db8611/src/main/java/OkSender.java#L53 puts the project key in a header instead of the query string. Can you clarify?

**Comment by stevecrozz** [comment]
I see now that this was already clarified in #16, but I think its still a bit odd that it seems to be an undocumented part of the Airbrake API. Did I miss the section that describes this header?

**Comment by vmihailenco** [comment]
What are you trying to achieve?

**Comment by stevecrozz** [comment]
I'm interested in knowing if this header is a reliable part of the Airbrake API. It seems like it must be because javabrake uses it, but the lack of mention in the API docs worried me. This is the only place I've seen it. Where did you learn about it?

**Comment by vmihailenco** [comment]
I work for Airbrake and that is how I've learned about it. And yes, X-Airbrake-Token is part of the API now.
