### ISSUE TITLE
Should not show the full file name in the trace

### ISSUE THREAD

**Issue by boris-petrov** [airbrake/javabrake#22]
The old Java notifier showed something like:

```
/RequestScope.java:289 → org.glassfish.jersey.process.internal.RequestScope.runInScope
/ServerRuntime.java:916 → org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume
/ServerRuntime.java:872 → org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume
/SourceFile:147 → com.my_company.SomeClass
```

While with `javabrake` the stacktrace is like:

```
/sun.reflect.NativeConstructorAccessorImpl:-2 → newInstance0
/sun.reflect.NativeConstructorAccessorImpl:62 → newInstance
/sun.reflect.DelegatingConstructorAccessorImpl:45 → newInstance
/java.lang.reflect.Constructor:423 → newInstance
/home/user/apache-tomcat/webapps/ROOT/WEB-INF/classes/com/my_company/SomeClass.class:37 → someMethod
```

I'm not sure I would call this a "security" issue but I think the old way was better.

**Comment by vmihailenco** [comment]
AFAIK javabrake shows `sun.reflect.NativeConstructorAccessorImpl`, not `/sun.reflect.NativeConstructorAccessorImpl`. Overall it tries to construct real path to the file which can be useful for Github integration etc. I don't expect this changed to be reverted except there is a good reason to do so.

**Comment by boris-petrov** [comment]
@vmihailenco - well, the good reason is for security - if requests are being made via HTTP (non-secure), anyone could sniff the traffic and figure out the file-system structure of the server.

Also, what I pasted were real traces, so the initial '/' is there.
