### ISSUE TITLE
How do I set the request url here

### ISSUE THREAD

**Issue by arashbi** [airbrake/javabrake#25]
In the old library I used to do 
`

    protected void setRequest(String url, String component) {
        super.setRequest(url, component);
    }

    @Override
    protected void request(Map<String, Object> request) {
        super.request(request);
    }
`
How do I do that here?

**Comment by vmihailenco** [comment]
Something like:

```java
Notice notice = notifier.buildNotice(exception);
notice.setContext("url", "http://...");
notice.setContext("component", "component name");
notifier.send(notice);
```

**Comment by sevo40** [comment]
protected void setRequest(String url, String component) {
    super.setRequest(url, component);
}

@Override
protected void request(Map<String, Object> request) {
    super.request(request);
}
