### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by simonwacker** [airbrake/javabrake#27]
Hallo!

How can I use Javabrake behind a proxy? Is there a way to configure the proxy setting of [OkSender.okhttp](https://github.com/airbrake/javabrake/blob/d68224109d9f4457b54aac382cecaf198acd8132/src/main/java/OkSender.java#L22)?

Best regards,
Simon.

**Comment by vmihailenco** [comment]
Hallo!

We could add some option like `Notifier.setProxy`, but it looks like I am just monkey-wrapping okhttp API. I guess the best solution would be to expose [OkSender.okhttp](https://github.com/airbrake/javabrake/blob/master/src/main/java/OkSender.java#L25-L30) instance to the users - I am just not sure how to do it right in Java idiomatic way. Suggestions are welcome.

**Comment by vmihailenco** [comment]
PS My current plan is
- make OkSender, OkSyncSender and OkAsyncSender public
- add static public method `OkSender.setOkHttpClient`

and the you have full control over okhttp client

**Comment by simonwacker** [comment]
Great to hear back from you! I reckon a public `setOkHttpClient` method is a Java idiomatic way. It would be great to also have a `getOkHttpClientBuilder` method that returns an `OkHttpClient.Builder` instance with sensible defaults for connect, read, and write timeouts.
