### ISSUE TITLE
GSON Illegal Reflective Access

### ISSUE THREAD

**Issue by keelerm84** [airbrake/javabrake#34]
When sending an error to airbrake, I am receiving the following warning (using OpenJDK 14.0.2):

```
WARNING: An illegal reflective access operation has occurred                                                                                                                    
WARNING: Illegal reflective access by com.google.gson.internal.reflect.UnsafeReflectionAccessor (file:/home/keelerm/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson
/2.8.6/9180733b7df8542621dc12e21e87557e8c99b8cb/gson-2.8.6.jar) to field java.lang.Throwable.detailMessage                                                                      
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.reflect.UnsafeReflectionAccessor                                                         
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations                                                                           
WARNING: All illegal access operations will be denied in a future release 
```

Are there any known solutions to this issue?

**Comment by AlexanderMann** [comment]
++ On this. I'm getting a different stack trace, but I think the core is that the version of GSON I need for my project is much higher than what this lib can handle.

I need at least `[com.google.code.gson/gson "2.8.5"]`. From what I can tell this library doesn't play nice with anything past `implementation 'com.google.code.gson:gson:1.7.2'`.

The gap between those deps looks to be about 8 years, not to mention the major and minor versions: https://mvnrepository.com/artifact/com.google.code.gson/gson

**Comment by scottsbaldwin** [comment]
Thanks @AlexanderMann for bumping this! We'll take a look.
