### ISSUE TITLE
Remove weird things from Spring Boot example

### ISSUE THREAD

**Issue by v-ladynev** [airbrake/javabrake#70]
1. Delete .vscode
2. Delete target
3. Delete `ServletInitializer`
4. Use `private final` for fields, use constructor dependency injection, don't use short names for fields
```java
    @Autowired
    WeatherService svc;
```
Becomes
```java
private final WeatherService weatherService;

@Autowired
public  WeatherController(WeatherService weatherService)
```
5. Don't use digits in method names, for example `String weather1(@PathVariable String location)`
6. Don't use the first uppercase letter in the method names, for example ` GetLocations()`
7. Don't use name in the `@Service` annotation, if you don't need it
```java
@Service("WeatherService")
```
becomes
```java
@Service
```

https://github.com/airbrake/javabrake/tree/master/examples/springboot

**Comment by sumitjoshi1989** [comment]
Thanks for your feedback. We have released a newer version of javabrake with the above changes. Please check.

**Comment by v-ladynev** [comment]
@sumitjoshi1989 Great! Thank you.
